version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - ../base/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: akhmed12/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: akhmed12/frontend:latest
    volumes:
      - ../frontend:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - ../sertf/certbot/conf:/etc/letsencrypt
      - ../sertf/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    env_file:
      - ./.env
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ../sertf/certbot/conf:/etc/letsencrypt
      - ../sertf/certbot/www:/var/www/certbot
volumes:
  static_value:
  media_value:

